blueprint:
  name: Irrigation Cycle
  description: Run irrigation zones sequentially with set durations
  domain: automation
  input:
    trigger_entity:
      name: Trigger Entity
      selector:
        entity: {}
    zone_1_time:
      name: Zone 1 Duration
      default: 0
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart

trigger:
  - platform: state
    entity_id: !input trigger_entity

action:
  - service: switch.turn_on
    target:
      entity_id: switch.irrigation_zone_1
    data:
      duration: !input zone_1_time
