run_zone:
  name: Run Zone
  description: Start a specific irrigation zone for a set duration.
  fields:
    zone:
      description: Zone number to run
      example: 1
    duration:
      description: Duration in seconds
      example: 300

stop_zone:
  name: Stop Zone
  description: Stop a specific irrigation zone immediately.
  fields:
    zone:
      description: Zone number to stop
      example: 1
